apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ErikGJacobsen/my-hello-world.git
    targetRevision: HEAD
    path: manifests  # Ensure your YAML files are in a `manifests` folder in your repo
  destination:
    server: https://kubernetes.default.svc
    namespace: my-hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
