apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-hello-world  # Fixed typo
spec:
  destination:
    namespace: test5
    server: https://kubernetes.default.svc
  source:
    path: dev
    repoURL: https://github.com/ErikGJacobsen/my-hello-world.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true