apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-hallo-world
  namespace: Erik
spec:
  project: default

  source:
    repoURL: https://github.com/ErikGJacobsen/my-hello-world.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: Erik

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true