apiVersion: v1
kind: Service
metadata:
  name: my-hello-world
  namespace: my-hello-world
spec:
  selector:
    app: my-hello-world
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31814
