apiVersion: v1
kind: Service
metadata:
  name: my-hello-world
  namespace: test5  # Ensure this matches your ArgoCD Application namespace
spec:
  type: NodePort
  selector:
    app: my-hello-world  # This must match your Deployment labels
  ports:
      nodePort: 31814  # Exposes the service externally on this port
      port: 8080        # Internal service port
      protocol: TCP
      targetPort: 8080  # Port on the application pod