apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"port":31814,"protocol":"TCP","serviceName":"default:test7-nodeport","allNodes":true}]
    field.cattle.io/targetWorkloadIds: '["default/test7"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2025-02-28T19:47:44Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: '2025-02-28T19:47:44Z'
  name: test7-nodeport
  namespace: default
  resourceVersion: '2194764'
  uid: d12f248a-0e63-41cf-8b72-e1caeaa40b60
spec:
  clusterIP: 10.43.127.35
  clusterIPs:
    - 10.43.127.35
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: test7
      nodePort: 31814
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-test7
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}