apiVersion: v1
kind: Service
metadata:
  name: my-hello-world
  namespace: test5  # Updated namespace
  labels:
    app.kubernetes.io/name: my-hello-world
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 31814  # Exposes the service on this port across all nodes
      port: 8080        # Internal cluster port
      protocol: TCP
      targetPort: 8080  # Port on the pod
  selector:
    app.kubernetes.io/name: my-hello-world